Gonen18
mlresearch/v83 pull request #4
Opened 2020-02-14 08:51 UTC by alongnn

2020-02-14 09:45 UTC, lawrennd requested changes
Hi Alon, as far as I can see this PDF still compiled with the old style file ...  it also doesn't conform to the right file naming convention. You should be able to see the original PDF in the repository, and you need to substitute for that. Does that make sens?

2020-02-14 10:40 UTC, alongnn commented
I added the new files into Gonem18a. It is ok? (I changed the main author
as well)

On Fri, Feb 14, 2020 at 11:45 AM Neil Lawrence <notifications@github.com>
wrote:

> *@lawrennd* requested changes on this pull request.
>
> Hi Alon, as far as I can see this PDF still compiled with the old style
> file ... it also doesn't conform to the right file naming convention. You
> should be able to see the original PDF in the repository, and you need to
> substitute for that. Does that make sens?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mlresearch/v83/pull/4?email_source=notifications&email_token=ADML3IYQY2UVDH7TQJJTKLLRCZR3BA5CNFSM4KVDRQA2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCVRSOVQ#pullrequestreview-358819670>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADML3IYERSE3FDHLESGNCJLRCZR3BANCNFSM4KVDRQAQ>
> .
>

2020-02-19 07:23 UTC, alongnn commented
Hi Neil,
I hope that my last submission was correct.
Thanks,
Alon

On Fri, Feb 14, 2020 at 12:39 PM Alon Gonen <alongnn@gmail.com> wrote:

> I added the new files into Gonem18a. It is ok? (I changed the main author
> as well)
>
> On Fri, Feb 14, 2020 at 11:45 AM Neil Lawrence <notifications@github.com>
> wrote:
>
>> *@lawrennd* requested changes on this pull request.
>>
>> Hi Alon, as far as I can see this PDF still compiled with the old style
>> file ... it also doesn't conform to the right file naming convention. You
>> should be able to see the original PDF in the repository, and you need to
>> substitute for that. Does that make sens?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/mlresearch/v83/pull/4?email_source=notifications&email_token=ADML3IYQY2UVDH7TQJJTKLLRCZR3BA5CNFSM4KVDRQA2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCVRSOVQ#pullrequestreview-358819670>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ADML3IYERSE3FDHLESGNCJLRCZR3BANCNFSM4KVDRQAQ>
>> .
>>
>

2020-02-27 12:17 UTC, lawrennd requested changes
HI Alon,

No, this still isn't correct, the gonem18a.pdf file needs changing directly, being updated for the new one (here it is listed as Gilad-Bachrach18.pdf) and the .yaml file needs editing. We don't need a new bib file here. 

The structure of each abstract should be clear from the filesystem, can you carefully check that your submission is conforming that before submitting the pull request?

Thanks!

Neil

2020-02-27 13:13 UTC, alongnn commented
The original problem was that my last name is not Gonem but Gonen. I would
like to change the main author to be Ran Gilad-Bachrach.
Thanks,
Alon

On Thu, Feb 27, 2020 at 2:17 PM Neil Lawrence <notifications@github.com>
wrote:

> *@lawrennd* requested changes on this pull request.
>
> HI Alon,
>
> No, this still isn't correct, the gonem18a.pdf file needs changing
> directly, being updated for the new one (here it is listed as
> Gilad-Bachrach18.pdf) and the .yaml file needs editing. We don't need a new
> bib file here.
>
> The structure of each abstract should be clear from the filesystem, can
> you carefully check that your submission is conforming that before
> submitting the pull request?
>
> Thanks!
>
> Neil
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mlresearch/v83/pull/4?email_source=notifications&email_token=ADML3IZC7W3T33Q4CI5NSXTRE6VPNA5CNFSM4KVDRQA2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCXFSHYQ#pullrequestreview-365634530>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADML3I3MXX4DTS2PD5FKVSTRE6VPNANCNFSM4KVDRQAQ>
> .
>

2020-02-27 15:31 UTC, lawrennd commented
Yes, but I don’t think we should be breaking links to original PDF and abstract page...



Neil
—
Professor Neil Lawrence
http://inverseprobability.com
________________________________
From: Alon Gonen <notifications@github.com>
Sent: Thursday, February 27, 2020 9:13:20 AM
To: mlresearch/v83 <v83@noreply.github.com>
Cc: Neil David Lawrence <ndl21@cam.ac.uk>; Comment <comment@noreply.github.com>
Subject: Re: [mlresearch/v83] Gilad-Bachrach18 (#4)

The original problem was that my last name is not Gonem but Gonen. I would
like to change the main author to be Ran Gilad-Bachrach.
Thanks,
Alon

On Thu, Feb 27, 2020 at 2:17 PM Neil Lawrence <notifications@github.com>
wrote:

> *@lawrennd* requested changes on this pull request.
>
> HI Alon,
>
> No, this still isn't correct, the gonem18a.pdf file needs changing
> directly, being updated for the new one (here it is listed as
> Gilad-Bachrach18.pdf) and the .yaml file needs editing. We don't need a new
> bib file here.
>
> The structure of each abstract should be clear from the filesystem, can
> you carefully check that your submission is conforming that before
> submitting the pull request?
>
> Thanks!
>
> Neil
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mlresearch/v83/pull/4?email_source=notifications&email_token=ADML3IZC7W3T33Q4CI5NSXTRE6VPNA5CNFSM4KVDRQA2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCXFSHYQ#pullrequestreview-365634530>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADML3I3MXX4DTS2PD5FKVSTRE6VPNANCNFSM4KVDRQAQ>
> .
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/mlresearch/v83/pull/4?email_source=notifications&email_token=AABAUWTXEJACNJGNZCRFXSTRE637BA5CNFSM4KVDRQA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENEKM6I#issuecomment-591963769>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AABAUWV5H3HC4X5H6OM2V6LRE637BANCNFSM4KVDRQAQ>.

2020-03-09 09:18 UTC, alongnn commented
I don’t understand. How the links can be broken?
Thanks,
Alon
On Feb 27, 2020, 5:38 PM +0200, Neil Lawrence <notifications@github.com>, wrote:
> Yes, but I don’t think we should be breaking links to original PDF and abstract page...
>
>
>
> Neil
> —
> Professor Neil Lawrence
> http://inverseprobability.com
> ________________________________
> From: Alon Gonen <notifications@github.com>
> Sent: Thursday, February 27, 2020 9:13:20 AM
> To: mlresearch/v83 <v83@noreply.github.com>
> Cc: Neil David Lawrence <ndl21@cam.ac.uk>; Comment <comment@noreply.github.com>
> Subject: Re: [mlresearch/v83] Gilad-Bachrach18 (#4)
>
> The original problem was that my last name is not Gonem but Gonen. I would
> like to change the main author to be Ran Gilad-Bachrach.
> Thanks,
> Alon
>
> On Thu, Feb 27, 2020 at 2:17 PM Neil Lawrence <notifications@github.com>
> wrote:
>
> > *@lawrennd* requested changes on this pull request.
> >
> > HI Alon,
> >
> > No, this still isn't correct, the gonem18a.pdf file needs changing
> > directly, being updated for the new one (here it is listed as
> > Gilad-Bachrach18.pdf) and the .yaml file needs editing. We don't need a new
> > bib file here.
> >
> > The structure of each abstract should be clear from the filesystem, can
> > you carefully check that your submission is conforming that before
> > submitting the pull request?
> >
> > Thanks!
> >
> > Neil
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/mlresearch/v83/pull/4?email_source=notifications&email_token=ADML3IZC7W3T33Q4CI5NSXTRE6VPNA5CNFSM4KVDRQA2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCXFSHYQ#pullrequestreview-365634530>,
> > or unsubscribe
> > <https://github.com/notifications/unsubscribe-auth/ADML3I3MXX4DTS2PD5FKVSTRE6VPNANCNFSM4KVDRQAQ>
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub<https://github.com/mlresearch/v83/pull/4?email_source=notifications&email_token=AABAUWTXEJACNJGNZCRFXSTRE637BA5CNFSM4KVDRQA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENEKM6I#issuecomment-591963769>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AABAUWV5H3HC4X5H6OM2V6LRE637BANCNFSM4KVDRQAQ>.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2025-09-04 06:55 UTC, closed without merging

2025-09-04 06:55 UTC, lawrennd commented
Problem fixed in a different PR.